name: Run C Program

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile
      run: gcc list.c -o list

    - name: Run
      run: echo -e "1\n3\n10\n20\n30\n4\n5" | ./list
